urls.py
from django.urls import path

from . import views

app_name = "flower"

urlpatterns = [
    path("showall/", views.showall, name="showall"),
    path("upload/", views.upload, name="upload"),
    path("result/", views.result, name="result"),
]

models.py
from django.db import models

# Create your models here.

class Image(models.Model):
    picture = models.ImageField(upload_to="images/")
    title = models.CharField(max_length=200, default="picture")
    first_name = models.CharField(max_length=20, default="")
    second_name = models.CharField(max_length=20, default="")
    third_name = models.CharField(max_length=20, default="")
    fourth_name = models.CharField(max_length=20, default="")
    fifth_name = models.CharField(max_length=20, default="")
    first_value = models.FloatField(default=0)
    second_value = models.FloatField(default=0)
    third_value = models.FloatField(default=0)
    fourth_value = models.FloatField(default=0)
    fifth_value = models.FloatField(default=0)

    def __str__(self):
        return self.title

forms.py
from django import forms

from .models import Image

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["picture"]

views.py
from django.shortcuts import redirect, render

from .forms import ImageForm

# Create your views here.
from .models import Image
from .recognition.recognize import main

def showall(request):
    images = Image.objects.all().order_by("-pk")
    context = {"images": images}
    return render(request, "flower/showall.html", context)

def upload(request):
    if request.method == "POST":
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            img = Image.objects.get(pk=Image.objects.count())
            output = main(img.picture)
            img.first_name = output[0][0]
            img.first_value = output[0][1]
            img.second_name = output[1][0]
            img.second_value = output[1][1]
            img.third_name = output[2][0]
            img.third_value = output[2][1]
            img.fourth_name = output[3][0]
            img.fourth_value = output[3][1]
            img.fifth_name = output[4][0]
            img.fifth_value = output[4][1]
            img.save()
            return redirect("flower:result")
    else:
        form = ImageForm()
    context = {"form": form}
    return render(request, "flower/upload.html", context)

def result(request):
    images = Image.objects.all().order_by("-pk")
    context = {"images": images[1:], "now_image": images[0]}
    return render(request, "flower/result.html", context)

templates/flower/result.html
<!DOCTYPE html>
<html>
  <head>
    <title>RESULT</title>
  </head>

  <body>
    <h1>結果</h1>
    <img src="{{ now_image.picture.url }}" width="200" />
    <h2>これは{{ now_image.first_name }}です!!</h2>
    <h1>詳細</h1>
    <h3>
      {{ now_image.first_name }}<br />
      {{ now_image.first_value }}%
    </h3>
    <h3>
      {{ now_image.second_name }}<br />
      {{ now_image.second_value }}%
    </h3>
    <h3>
      {{ now_image.third_name }}<br />
      {{ now_image.third_value }}%
    </h3>
    <h3>
      {{ now_image.fourth_name }}<br />
      {{ now_image.fourth_value }}%
    </h3>
    <h3>
      {{ now_image.fifth_name }}<br />
      {{ now_image.fifth_value }}%
    </h3>

    <h1>過去の結果</h1>
    <table>
      <thead>
        <tr>
          <th>画像 \ 確率</th>
          <th>1st</th>
          <th>2nd</th>
          <th>3rd</th>
          <th>4th</th>
          <th>5th</th>
        </tr>
      </thead>
      <tbody>
        {% for image in images %}
        <tr>
          <th><img src="{{ image.picture.url }}" height="70" /></th>
          <td>
            <h3>
              {{ image.first_name }}<br />
              {{ image.first_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.second_name }}<br />
              {{ image.second_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.third_name }}<br />
              {{ image.third_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.fourth_name }}<br />
              {{ image.fourth_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.fifth_name }}<br />
              {{ image.fifth_value }}%
            </h3>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br />
    <a href="{% url 'flower:upload' %}">Upload more</a>
    <br />
  </body>
</html>

templates/flower/showall.html
<!DOCTYPE html>
<html>
  <head>
    <title>RESULT</title>
  </head>

  <body>
    <h1>過去の結果一覧</h1>
    <table>
      <thead>
        <tr>
          <th>画像 \ 確率</th>
          <th>1st</th>
          <th>2nd</th>
          <th>3rd</th>
          <th>4th</th>
          <th>5th</th>
        </tr>
      </thead>
      <tbody>
        {% for image in images %}
        <tr>
          <th><img src="{{ image.picture.url }}" height="70" /></th>
          <td>
            <h3>
              {{ image.first_name }}<br />
              {{ image.first_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.second_name }}<br />
              {{ image.second_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.third_name }}<br />
              {{ image.third_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.fourth_name }}<br />
              {{ image.fourth_value }}%
            </h3>
          </td>
          <td>
            <h3>
              {{ image.fifth_name }}<br />
              {{ image.fifth_value }}%
            </h3>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br />
    <a href="{% url 'flower:upload' %}">Upload more</a>
    <br />
  </body>
</html>

templates/flower/upload.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>FLOWER SEACHER</title>
  </head>

  <body>
    <h2>花検索アプリ</h2>
    <h1>Flower Searcher</h1>
    <p>
      Flower Searcherは、入力された花の種類を認識するアプリです。
      <br />
      認識したい花の画像をアップロードしてみましょう。
    </p>
    <form
      enctype="multipart/form-data"
      action="{% url 'flower:upload' %}"
      method="POST"
    >
      {% csrf_token %} {{form.as_p}}
      <br />
      <button type="submit">Upload</button>
      <a href="{% url 'flower:showall' %}">過去の結果一覧を見る</a>
    </form>
  </body>
</html>